# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-30 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kingdom name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ruler's personality", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('ruler', models.TextField(default='')),
                ('kingdom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receiver.Kingdom')),
                ('personality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receiver.Personality')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Utopian Race', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receiver.Race'),
        ),
    ]
